### ISSUE TITLE
CAN NOT OPEN ANNE PRO 2's SETTING ON UBUNTU

### ISSUE THREAD

**Issue by hasagi6969** [obinslab/obinslab-starter-translations#9]
Hello dev team, 
I have bought an Anne Pro 2 for months. I appreciated this keyboard and its software on Windows, these guys work perfectly, but my main system is Linux and I got some trouble when use the Obinslab starter on my Ubuntu 18.04 machine. I can not open the setting of the keyboard. Hope you guys will reply soon. thank you
By the way this is the screenshot of the issues
![image](https://user-images.githubusercontent.com/36883431/56648294-47b60f80-66ad-11e9-9c4e-97b9f4d7ba66.png)

**Comment by obinslab** [comment]
##### Ubuntu/Debian

Most Linux distros use `udev` to manage access to physical devices. To allow non-root access our keyboard, 

before using Obenslab Starter for the first time, we need the following operations:

1. Create file`obinslab-starter.rules` under  `/etc/udev/rules.d`

   ```bash
   SUBSYSTEM=="input", GROUP="input", MODE="0666"
   
   # For ANNE PRO 2
   SUBSYSTEM=="usb", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="8008", MODE="0666", GROUP="plugdev"
   KERNEL=="hidraw*", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="8008", MODE="0666", GROUP="plugdev"
   SUBSYSTEM=="usb", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="8009", MODE="0666", GROUP="plugdev"
   KERNEL=="hidraw*", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="8009", MODE="0666", GROUP="plugdev"
   
   ## For ANNE PRO
   SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5710", MODE="0666", GROUP="plugdev"
   KERNEL=="hidraw*", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5710", MODE="0666", GROUP="plugdev"
   ```

2. Reload rules by execute: `sudo udevadm control --reload-rule

3. Unplug and replug keyboard

**Comment by obinslab** [comment]
I apologize for your confusion. 

We plan to improve this problem and let this operation be performed automatically. 

By the way, it's a translation project, please send email to service@obins.net for a quick response.

If it slove your problem, please let me know, and then I close this issue.

Thank you very much. :)

**Comment by hasagi6969** [comment]
thank you for replying, everything work well now.
thanks a lot

**Comment by LinoMota** [comment]
it worked for me, thx

**Comment by rbroggi** [comment]
I suggest to add it to your official software documentation: I was about to return the product because the software did not work under linux.

**Comment by rbroggi** [comment]
I also suggest you to add the installation process for the `.deb` package

**Comment by obinslab** [comment]
Hi
Obinskit supports Linux.



Best Regards

太仓知更鸟信息技术有限公司
Email: ***@***.***
Twitter: twitter.com/HexcoreIntl
Web：www.hexcore.xyz
Add: 江苏省太仓市科教新城大学科技园健雄路20号

本信件属于太仓知更鸟信息技术有限公司的业务邮件，可能含有商业秘密及其他重要公司信息内容，其受到相关商业秘密保护法律法规及太仓知更鸟信息技术有限公司保密制度保护和约束，不当或违法的转移本邮件会受到不同程度的责任追究，发送人和接收人均在可能被追究责任的范围内，因此，请谨慎处理。如您非接收人，请即联系我们，并请不要阅读、复制或向第三人披露本邮件。谢谢！ 
This email belongs to Taicang zhigengniao Information Technology Co., Ltd., may contain trade secrets and other important company information, which are protected and restricted by relevant laws and regulations for the protection of business secrets, and secrete system of the taicang zhigengniao Information Technology Co., Ltd.Improper or illegal transfer of this email will be affected by different levels of responsibility,the sender and receiver may be called to account, so please be careful for handling. If you are not the receiver, please contact us, and please do not read, copy or disclose this email to third parties. Thank you very much!
 
 
From: Rodrigo Broggi
Date: 2021-12-02 02:39
To: obinslab/obinslab-starter-translations
CC: obinslab; Comment
Subject: Re: [obinslab/obinslab-starter-translations] CAN NOT OPEN ANNE PRO 2's SETTING ON UBUNTU (#9)
I suggest to add it to your official software documentation: I was about to return the product because the software did not work under linux.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rbroggi** [comment]
Since it supports linux, wold 

> Hi Obinskit supports Linux. Best Regards 太仓知更鸟信息技术有限公司 Email: ***@***.*** Twitter: twitter.com/HexcoreIntl Web：[www.hexcore.xyz](http://www.hexcore.xyz) Add: 江苏省太仓市科教新城大学科技园健雄路20号 本信件属于太仓知更鸟信息技术有限公司的业务邮件，可能含有商业秘密及其他重要公司信息内容，其受到相关商业秘密保护法律法规及太仓知更鸟信息技术有限公司保密制度保护和约束，不当或违法的转移本邮件会受到不同程度的责任追究，发送人和接收人均在可能被追究责任的范围内，因此，请谨慎处理。如您非接收人，请即联系我们，并请不要阅读、复制或向第三人披露本邮件。谢谢！ This email belongs to Taicang zhigengniao Information Technology Co., Ltd., may contain trade secrets and other important company information, which are protected and restricted by relevant laws and regulations for the protection of business secrets, and secrete system of the taicang zhigengniao Information Technology Co., Ltd.Improper or illegal transfer of this email will be affected by different levels of responsibility,the sender and receiver may be called to account, so please be careful for handling. If you are not the receiver, please contact us, and please do not read, copy or disclose this email to third parties. Thank you very much! From: Rodrigo Broggi Date: 2021-12-02 02:39 To: obinslab/obinslab-starter-translations CC: obinslab; Comment Subject: Re: [obinslab/obinslab-starter-translations] CAN NOT OPEN ANNE PRO 2's SETTING ON UBUNTU (#9) I suggest to add it to your official software documentation: I was about to return the product because the software did not work under linux. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


I think it would be worth putting the results of this thread in the official product web page along with installation guides for linux users. What do you think?

**Comment by LBreda** [comment]
My Anne Pro 2 has `a293` as the product ID. It should be added to the udev rule.

**Comment by Osten** [comment]
mine also, product ID  `a293` worked only when checking with `udevadm info` on the device path (`lsusb` was wrong)
